environment:

  matrix:

    - PYTHON: "C:\\Python27"
#    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python38"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install pytest"
  - "%PYTHON%\\python.exe -m pip install cryptography"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest -v -l test_syncobj.py"
